//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoInfo
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public string Created { get; set; }
        public Nullable<bool> CurrStatus { get; set; }
    }
}
